career_options = [
    "Software Developer",
    "Hardware Engineer",
    "Network Engineer",
    "Systems Analyst",
    "Data Scientist",
    "Cybersecurity Analyst",
    "Artificial Intelligence Engineer",
    "Web Developer",
    "Mobile App Developer",
    "Cloud Computing Engineer",
    "Database Administrator",
    "Embedded Systems Engineer",
    "Robotics Engineer",
    "IoT (Internet of Things) Developer",
    "Game Developer",
    "UI-UX Designer",
    "Quality Assurance Engineer",
    "Project Manager (IT)",
    "Business Analyst (IT)",
    "IT Consultant",
    "Civil Engineer",
    "Structural Engineer",
    "Environmental Engineer",
    "Geotechnical Engineer",
    "Transportation Engineer",
    "Electrical Engineer",
    "Electronics Engineer",
    "Power Systems Engineer",
    "Renewable Energy Engineer",
    "Control Systems Engineer",
    "Aerospace Engineer",
    "Mechanical Engineer",
    "Automotive Engineer",
    "Materials Engineer",
    "Production Engineer",
    "Chemical Engineer",
    "Process Engineer",
    "Biomedical Engineer",
    "Pharmaceutical Engineer",
    "Processing Engineer",
    "Telecommunication Engineer",
    "Network Administrator",
    "Technical Writer",
    "Patent Analyst",
    "Sales Engineer",
    "Supply Chain Manager",
    "Operations Manager",
    "Construction Manager",
    "Research and Development Engineer",
    "Entrepreneur Founder",
]

career_options_comp = [
    "Materials Engineer"
]
